language: php
php:
  - 5.5
  - 5.4
install:
  - composer install --prefer-dist --dev
  - composer require --dev "codeception/codeception:2.0.0-beta"
  - gem install mailcatcher
before_script:
  - mailcatcher
  - mysql -e 'create database dektrium_test;'
  - sed -i 's/\/..\/..\/..\//\/..\//g' tests/_bootstrap.php
  - php tests/yii migrate/up --interactive=0
  - vendor/bin/codecept build
script: vendor/bin/codecept run